### ISSUE TITLE
Dynamic node_id?

### ISSUE THREAD

**Issue by SlothCroissant** [ryanjohnsontv/node-red-contrib-ha-inovelli-manager#16]
Hey there, love the work you've done here to radically simplify scene management with Inovelli switches! Quick ask - is it possible to use dynamic values for the node_id in the scene manager node? Ref:

![image](https://user-images.githubusercontent.com/5846854/134838608-266799c4-fa3d-4415-a806-85cd1dd25d7a.png)

When I check the value of `msg.payload.event.node_id` using a debug node, it shows the proper node_id integer. 

![image](https://user-images.githubusercontent.com/5846854/134838510-cc55e9f7-c52d-424e-99f8-a9c5c3eb4783.png)

And when I manually enter that integer into the scene manager config, it works great. But when I try to use `msg.payload.event.node_id` in the node config, I can't seem to get it to work. 

Any advice? Thanks!

**Comment by ryanjohnsontv** [comment]
Currently that field uses the provided node ID, or a list of node IDs, to send the value notification message to the proper node output. Perhaps I'm not understanding, but in its current state leaving that wide open it would try to process every single Z-Wave value notification, meaning if you have different switch types in your Z-Wave network then they would be incorrectly sorted through the node.
I'm very interested to understand your use case because I want this to be one-size-fits-all solution for people. If it's of any interest, for my set up I have all of my dimmer node IDs in a dimmer scene-manager node and each output of that node feeds to a specific function node which then handles automatons based on the msg.payload.event.node_id value. Not sure if that's of any help to you
![Screen Shot 2021-09-26 at 10 07 04 PM](https://user-images.githubusercontent.com/43426700/134839831-1aeff511-d109-4939-bd9a-c52632d3ffb6.png)
.

**Comment by SlothCroissant** [comment]
Thanks for the reply! My use case may be somewhat unique, in that the *only* scene capable devices in my network are LZW30-SN switches. 

So I'd love to be able to have options for "if ANY device is 5x tapped, do X" situations without having to hard code node IDs wherever possible. Or some other upstream filtering that's not dependent on hard coded node ID. 

Hope that helps clarify!

**Comment by ryanjohnsontv** [comment]
Brilliant, gotcha! I'm wrapping up for the evening, but tomorrow I can add a passthrough toggle that disables the Node ID field and just sends through any value notification message.

**Comment by SlothCroissant** [comment]
Awesome! Thanks for the quick turnaround! Once you're set, let me know and I'll be happy to test and confirm for ya.

**Comment by ryanjohnsontv** [comment]
Just released! Let me know if you have any issues.
https://github.com/ryanjohnsontv/node-red-contrib-ha-inovelli-manager/releases/tag/v0.1.1

**Comment by SlothCroissant** [comment]
Works like a charm!

I can now use a switch statement to set a variable of target devices, and the one node processes them all:

![image](https://user-images.githubusercontent.com/5846854/135001238-1f736961-3dba-4543-90e6-4449cec05b0f.png)
