### ISSUE TITLE
FR - Multicast for LED manager and support for WHITE

### ISSUE THREAD

**Issue by MRobi1** [ryanjohnsontv/node-red-contrib-ha-inovelli-manager#19]
I know I already made an FR for multicast on the notification node, could this also be added to the LED manager node? 
Back on Hubitat, instead of using notifications I would change the default LED color to avoid the momentary change back to the default LED when interacting with the switch. I think this could be accomplished here as well on zwavejs.

Also, is there support for setting the LED to white on the slider? I'm not seeing it there. It could make a nice little night light :)

Thanks again!

**Comment by ryanjohnsontv** [comment]
Great timing, I’m almost done with a complete revamp of the LED manager mode, multicast included.
I’m a bit confused on setting the LEDs to white, because it should be possible, and they even mention setting it to white in the SmartThings documentation, but I haven’t been able to set it to white with any of the parameters in the three HA Z-Wave integrations.

**Comment by ryanjohnsontv** [comment]
New LED manager incoming: https://github.com/ryanjohnsontv/node-red-contrib-ha-inovelli-manager/releases/tag/v0.2.0
